// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDCv3b_XF0izW4yYtKn2wnaf681ZLoKs',
    appId: '1:372363288591:web:8affe89e6392135564c37a',
    messagingSenderId: '372363288591',
    projectId: 'jain-matrimony-buray',
    authDomain: 'jain-matrimony-buray.firebaseapp.com',
    databaseURL: 'https://jain-matrimony-buray-default-rtdb.firebaseio.com',
    storageBucket: 'jain-matrimony-buray.firebasestorage.app',
    measurementId: 'G-7LL501K6G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_zZvHYvagl2su2OAkmP5ziOUPvJ5_qw',
    appId: '1:343458217443:android:df4fabef59cdfeeddfb4d6',
    messagingSenderId: '343458217443',
    projectId: 'k-maratha',
    databaseURL: 'https://k-maratha.firebaseio.com',
    storageBucket: 'k-maratha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvnyhsZEGMCCEl2WdK-CuxU2jpOpfeac',
    appId: '1:372363288591:ios:365e28e71db084d164c37a',
    messagingSenderId: '372363288591',
    projectId: 'jain-matrimony-buray',
    databaseURL: 'https://jain-matrimony-buray-default-rtdb.firebaseio.com',
    storageBucket: 'jain-matrimony-buray.firebasestorage.app',
    iosBundleId: 'com.example._96kuliapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvnyhsZEGMCCEl2WdK-CuxU2jpOpfeac',
    appId: '1:372363288591:ios:365e28e71db084d164c37a',
    messagingSenderId: '372363288591',
    projectId: 'jain-matrimony-buray',
    databaseURL: 'https://jain-matrimony-buray-default-rtdb.firebaseio.com',
    storageBucket: 'jain-matrimony-buray.firebasestorage.app',
    iosBundleId: 'com.example._96kuliapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDCv3b_XF0izW4yYtKn2wnaf681ZLoKs',
    appId: '1:372363288591:web:3b9854027164cbaa64c37a',
    messagingSenderId: '372363288591',
    projectId: 'jain-matrimony-buray',
    authDomain: 'jain-matrimony-buray.firebaseapp.com',
    databaseURL: 'https://jain-matrimony-buray-default-rtdb.firebaseio.com',
    storageBucket: 'jain-matrimony-buray.firebasestorage.app',
    measurementId: 'G-0YHL9CZSGR',
  );
}
